WepSiteBanHang/WepSiteBanHang/Models/KHACHHANG.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WepSiteBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        public string TENKH { get; set; }
        public string DIACHI { get; set; }
        public string EMAIL { get; set; }
        public string SDT { get; set; }
        public Nullable<decimal> MATHANHVIEN { get; set; }
        public decimal MAKH { get; set; }
    
        public virtual THANHVIEN THANHVIEN { get; set; }
    }
}

WepSiteBanHang/WepSiteBanHang/Areas/Admin/Controllers/DangNhapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WepSiteBanHang.Models;
using System.IO;
namespace WepSiteBanHang.Areas.Admin.Controllers
{
   
    public class DangNhapController : Controller
    {
        DBBanHangEntities db = new  DBBanHangEntities();
        // GET: Admin/DangNhap
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult DangNhap()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangNhap(FormCollection collection)
        {
            var tk = collection["taikhoan"];
            var mk = collection["password"];
            if (String.IsNullOrEmpty(tk))
            {
                ViewData["Loi1"] = "Chưa nhập tài khoản";
            }
            else
            {
                if (String.IsNullOrEmpty(mk))
                {
                    ViewData["Loi2"] = "Chưa nhập mật khẩu";
                }
                else
                {
                    QUANLY ad = db.QUANLies.SingleOrDefault(m => m.TENTK == tk && m.PASS == mk);
                    if (ad != null)
                    {
                        Session["Admin"] = ad;
                        return RedirectToAction("Index", "TrangAdmin");
                    }
                    else
                    {
                        ViewData["Loi2"] = "Tài khoản hoặc mật khẩu sai";
                    }
                }
            }

            return View();
        }
        public ActionResult HienThiTK()
        {
            var ad = (QUANLY)Session["Admin"];
            return PartialView(ad);
        }
        public ActionResult DangXuat()
        {
            Session["Admin"] = null;
            return RedirectToAction("DangNhap", "DangNhap");
        }
    }
}

WepSiteBanHang/WepSiteBanHang/Controllers/DangNhapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WepSiteBanHang.Models;

namespace WepSiteBanHang.Controllers
{
    public class DangNhapController : Controller
    {
        // GET: DangNhap
        DBBanHangEntities db = new DBBanHangEntities();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult DangNhap()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangNhap(FormCollection collection)
        {   
            var tk = collection["taikhoan"];
            var mk = collection["password"];
            if (String.IsNullOrEmpty(tk))
            {
                ViewData["Loi1"] = "Chưa nhập tài khoản";
            }
            else
            {
                if (String.IsNullOrEmpty(mk))
                {
                    ViewData["Loi2"] = "Chưa nhập mật khẩu";
                }
                else
                {
                    QUANLY ad = db.QUANLies.SingleOrDefault(m => m.TENTK == tk && m.PASS == mk);
                    if (ad != null)
                    {
                        Session["Admin"] = ad;
                        return RedirectToAction("Index", "TrangAdmin");
                    }
                    else
                    {
                        ViewData["Loi2"] = "Tài khoản hoặc mật khẩu sai";
                    }
                }
            }

            return View();
        }
        public ActionResult HienThiTK()
        {
            var ad = (QUANLY)Session["Admin"];
            return PartialView(ad);
        }
        public ActionResult DangXuat()
        {
            Session["Admin"] = null;
            return RedirectToAction("DangNhap", "DangNhap");
        }
    }
}

WepSiteBanHang/WepSiteBanHang/Controllers/KhachHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WepSiteBanHang.Models;
using System.Net;
using System.Runtime.Serialization.Json;
using System.IO;
using System.Text;

namespace WepSiteBanHang.Controllers
{
    public class KhachHangController : Controller
    {
        DBBanHangEntities db = new DBBanHangEntities();
        // GET: KhachHang
        public ActionResult Index()
        {
            return View();
        }
        
        private bool IsValidRecaptcha(string recaptcha)
        {
            if (string.IsNullOrEmpty(recaptcha))
            {
                return false;
            }
            var secretKey = "6LeF-QMTAAAAAOw8M2RTtxoY6ifOhhUb4GlXpdB3";//Mã bí mật
            string remoteIp = Request.ServerVariables["REMOTE_ADDR"];
            string myParameters = String.Format("secret={0}&response={1}&remoteip={2}", secretKey, recaptcha, remoteIp);
            RecaptchaResult captchaResult;
            using (var wc = new WebClient())
            {
                wc.Headers[HttpRequestHeader.ContentType] = "application/x-www-form-urlencoded";
                var json = wc.UploadString("https://www.google.com/recaptcha/api/siteverify", myParameters);
                var js = new DataContractJsonSerializer(typeof(RecaptchaResult));
                var ms = new MemoryStream(Encoding.ASCII.GetBytes(json));
                captchaResult = js.ReadObject(ms) as RecaptchaResult;
                if (captchaResult != null && captchaResult.Success)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
        }

        [HttpPost]
        public ActionResult Index(FormCollection form)
        {
            if (IsValidRecaptcha(Request["g-recaptcha-response"]))
            {
                ViewBag.Status = "Mã Recaptcha hợp lệ";
            }
            else
            {
                ViewBag.Status = "Không hợp lệ";
            }
            return View();
        }

        [HttpGet]
        public ActionResult DangKy()
        {
            return PartialView();

        }


        [HttpPost]
        public ActionResult Dangky(FormCollection col, THANHVIEN tv)
        {
            if (IsValidRecaptcha(Request["g-recaptcha-response"]))
            {
                var ten = col["Username"];
                var matkhau = col["Password"];
                var Email = col["Email"];
                var dt = col["Phone"];
                var hoten = col["hoten"];
                var diachi = col["DiaChi"];
                tv.TAIKHOAN = ten;
                tv.MATKHAU = matkhau;
                tv.EMAIL = Email;
                tv.SDT = dt;
                tv.HOTEN = hoten;
                tv.DIACHI = diachi;
                db.THANHVIENs.Add(tv);
                db.SaveChanges();
                return this.DangKy();

            }
            else
            {
                ViewBag.Status = "Không hợp lệ";
                return View();
            }


        }
        [HttpGet]
        public ActionResult Dangnhap()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Dangnhap(FormCollection collection)
        {
            // Gán các giá trị người dùng nhập liệu cho các biến 
            var tendn = collection["User"];
            var matkhau = collection["Pass"];

            if (String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi1"] = "Phải nhập tên đăng nhập hoặc mật khẩu sai";
            }
            else if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi2"] = "Phải nhập tên đăng nhập hoặc mật khẩu sai";
            }

            else
            {
                //Gán giá trị cho đối tượng được tạo mới (kh)

                THANHVIEN tv = db.THANHVIENs.First(n => n.TAIKHOAN == tendn && n.MATKHAU == matkhau);

                if (tv != null)
                {
                    // ViewBag.Thongbao = "Chúc mừng đăng nhập thành công";
                    Session["Thanhvien"] = tv;

                    return RedirectToAction("Index", "Home");
                }
                else
                    ViewBag.Thongbao = "Tên đăng nhập hoặc mật khẩu không đúng";
            }
            return View();
        }
        public ActionResult Thoattk()
        {
            Session["Thanhvien"] = null;
            return RedirectToAction("Index", "Home");
        }
        [HttpGet]
        public ActionResult Xacnhanemail()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Xacnhanemail(FormCollection collection)
        {
            var ten = collection["tentk"];
            var email = collection["xnemail"];
            SendMail(ten, email);
            return RedirectToAction("Index", "Home");
        }
        protected void SendMail(string ten, string email)
        {
            THANHVIEN tv = db.THANHVIENs.First(n => n.TAIKHOAN == ten && n.EMAIL == email);
            var fromAddress = "sulo42229@gmail.com";
            // any address where the email will be sending
            var toAddress = email.ToString();
            //Password of your Email address
            const string fromPassword = "nhan2066";
            // Passing the values and make a email formate to display
            string subject = "Bạn đã yêu cầu tìm lại mật khẩu";
            string body = "Mật khẩu của bạn " + tv.MATKHAU + "\n";
            // smtp settings
            var smtp = new System.Net.Mail.SmtpClient();
            {
                smtp.Host = "smtp.gmail.com";
                smtp.Port = 587;
                smtp.EnableSsl = true;
                smtp.DeliveryMethod = System.Net.Mail.SmtpDeliveryMethod.Network;
                smtp.Credentials = new NetworkCredential(fromAddress, fromPassword);
                smtp.Timeout = 20000;
            }
            // Passing values to smtp object
            smtp.Send(fromAddress, toAddress, subject, body);
        }
    }
}

WepSiteBanHang/WepSiteBanHang/Views/KhachHang/DangKy.cshtml
<script src='https://www.google.com/recaptcha/api.js'></script>
<div class="form">
    <h2>Tạo Tài Khoản</h2>
    <form action="#" method="post" id="demo">
        <input type="text" name="Username" placeholder="Nhập Tài Khoản" required=" ">
        <input type="password" name="Password" placeholder="Nhập Mật Khẩu" required=" ">
        <input type="email" name="Email" placeholder="Email Address" required=" ">
        <input type="text" name="Phone" placeholder="Số Điện Thoại" required=" ">
        <input type="text" name="hoten" placeholder="Họ Tên" required=" ">
        <input type="text" name="diachi" placeholder="Địa Chỉ" required=" ">

        <div class="g-recaptcha" data-sitekey="6LcA1wsUAAAAAFjamjGvtMfKLFbAO8SN5R5wMzG0"></div>
        <input type="submit" value="Đăng Ký">
    </form>
</div>
<script src="~/Scripts/jquery-1.11.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>
<script type="text/javascript">

    $(document).ready(function () {

        $("#demo").validate({
            rules: {
                Username: "required",
                Password: {
                    required: true,
                    minlength: 5,
                },
                hoten: "required",

                Phone: {
                    required: true,
                    number: true,
                    maxlength: 11,
                },
                diachi: {
                    required: true,
                    minlength: 2
                },
                Email: {
                    required: true,
                    email: true
                },
            },
            messages: {
                Username: "Vui lòng nhập Tài Khoản",
                Password: {
                    required: "Vui lòng nhập Password",
                    minlength: "Mật Khẩu Quá ít",

                },
                hoten: "Vui lòng nhập Họ Tên",
                Phone: {
                    required: "Vui lòng nhập số điện thoại",
                    maxlength: "Số máy quý khách vừa nhập là số không có thực",
                    number: "Không đươc để Kí Hiệu hoặc chữ "
                },
                diachi: {
                    required: "Vui lòng nhập địa chỉ",
                    minlength: "Địa chỉ ngắn vậy"
                },
                Email: {
                    required: "Vui Lòng Nhập Mail",
                    minlength: "Mail Không có thực",
                },


            }
        });
    });
</script>

WepSiteBanHang/WepSiteBanHang/Views/KhachHang/Dangnhap.cshtml
@{
    ViewBag.Title = "Dangnhap";
    Layout = "~/Views/Layout/ProductLayout.cshtml";
}

<div class="w3l_banner_nav_right">
    <div class="w3_login">
        <h3>Đăng nhập và Đăng ký tài khoản</h3>
        <div class="w3_login_module">
            <div class="module form-module">
                <div class="toggle">
                    <i class="fa fa-times fa-pencil"></i>
                    <div class="tooltip">Đăng ký</div>
                </div>
                <div class="form">
                    <h2>Đăng Nhập Tài Khoản</h2>
                    <form action="#" method="post">
                        <input type="text" name="User" placeholder="Nhập Tài Khoản" required=" ">
                        <input type="password" name="Pass" placeholder="Nhập Mật Khẩu" required=" ">
                        @ViewData["Loi3"]
                        <input type="submit" value="Đăng Nhập">
                    </form>
                </div>
                @Html.Action("DangKy", "KhachHang")
                <div class="cta"><a href="@Url.Action("Xacnhanemail", "KhachHang")">Quên mật khẩu</a></div>
            </div>
        </div>
        <script>
				$('.toggle').click(function(){
				  // Switches the Icon
				  $(this).children('i').toggleClass('fa-pencil');
				  // Switches the forms
				  $('.form').animate({
					height: "toggle",
					'padding-top': 'toggle',
					'padding-bottom': 'toggle',
					opacity: "toggle"
				  }, "slow");
				});
        </script>
    </div>
    <!-- //login -->
</div>

WepSiteBanHang/WepSiteBanHang/Views/KhachHang/Xacnhanemail.cshtml
@{
    ViewBag.Title = "Xacnhanemail";
    Layout = "~/Views/Layout/ProductLayout.cshtml";
}
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>
<form action="#" id="demo" method="post">
<div style="margin:auto;text-align:center;width:40%">
    <h2>Tìm lại mật khẩu</h2>
    <div class="form-group">
        <label>Tên đăng của bạn</label>
        <input type="text" name="tentk" id="txtName" class="form-control" required />
    </div>
    <div class="form-group">
        <label>Email của tài khoản</label>
        <input type="text" name="xnemail" class="form-control" required />
    </div>
    <button id="btnSend" class="btn btn-success">Gửi di</button>
</div>
</form>
<script type="text/javascript">

    $(document).ready(function () {

        $("#demo").validate({
            rules: {
                tentk: "required",

                xnemail: {
                    required: true,
                    email: true
                },


            },
            messages: {
                tentk: "Vui lòng nhâp Tài Khoản",
                xnemail: {
                    required: "Vui Lòng Nhập Mail",
                    minlength: "Mail Không có thực",
                    email:"Xin Hãy Nhập Ðúng địa chỉ Email"
                },



            }
        });
    });
</script>