WepSiteBanHang/WepSiteBanHang/Areas/Admin/Controllers/QuanLyDonHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using WepSiteBanHang.Models;
namespace WepSiteBanHang.Areas.Admin.Controllers
{
    public class QuanLyDonHangController : Controller
    {
        // GET: Admin/QuanLyDonHang
        DBBanHangEntities db = new DBBanHangEntities();
        public ActionResult ChuaThanhToan()
        {
            ViewBag.SoNguoiTruyCap = HttpContext.Application["SoNguoiTruyCap"].ToString();//Số lượng người truy cập từ application đã được tạo
            ViewBag.SoLuongNguoiOnline = HttpContext.Application["SoNguoiDangOnline"].ToString();//Lấy số lượng người đang truy cập
            ViewBag.TongDoanhThu = ThongKeTongDoanhThu();//Thống kê tổng doanh thu
            ViewBag.TongDDH = ThongKeDonHang();//Thống kê dơn hàng
            ViewBag.TongThanhVien = ThongKeThanhVien();//Thống kê thành viên
            //Lấy danh sách các đơn hàng Chưa duyệt
            var lst = db.DONDATHANGs.Where(n => n.DATHANHTOAN == 0).OrderBy(n => n.NGAYDAT);
            return View(lst);
        }
        public ActionResult ChuaGiao()
        {
            ViewBag.SoNguoiTruyCap = HttpContext.Application["SoNguoiTruyCap"].ToString();//Số lượng người truy cập từ application đã được tạo
            ViewBag.SoLuongNguoiOnline = HttpContext.Application["SoNguoiDangOnline"].ToString();//Lấy số lượng người đang truy cập
            ViewBag.TongDoanhThu = ThongKeTongDoanhThu();//Thống kê tổng doanh thu
            ViewBag.TongDDH = ThongKeDonHang();//Thống kê dơn hàng
            ViewBag.TongThanhVien = ThongKeThanhVien();//Thống kê thành viên
            //Lấy danh sách đơn hàng chưa giao 
            var lstDSDHCG = db.DONDATHANGs.Where(n => n.TINHTRANGGIAO == 0 && n.DATHANHTOAN == 0).OrderBy(n => n.NGAYGIAO);
            return View(lstDSDHCG);
        }
        public ActionResult DaGiaoDaThanhToan()
        {
            ViewBag.SoNguoiTruyCap = HttpContext.Application["SoNguoiTruyCap"].ToString();//Số lượng người truy cập từ application đã được tạo
            ViewBag.SoLuongNguoiOnline = HttpContext.Application["SoNguoiDangOnline"].ToString();//Lấy số lượng người đang truy cập
            ViewBag.TongDoanhThu = ThongKeTongDoanhThu();//Thống kê tổng doanh thu
            ViewBag.TongDDH = ThongKeDonHang();//Thống kê dơn hàng
            ViewBag.TongThanhVien = ThongKeThanhVien();//Thống kê thành viên
            //Lấy danh sách đơn hàng chưa giao 
            var lstDSDHCG = db.DONDATHANGs.Where(n => n.TINHTRANGGIAO == 1 && n.DATHANHTOAN == 1);
            return View(lstDSDHCG);
        }

        [HttpGet]
        public ActionResult DuyetDonHang(int? id)
        {
            ViewBag.SoNguoiTruyCap = HttpContext.Application["SoNguoiTruyCap"].ToString();//Số lượng người truy cập từ application đã được tạo
            ViewBag.SoLuongNguoiOnline = HttpContext.Application["SoNguoiDangOnline"].ToString();//Lấy số lượng người đang truy cập
            ViewBag.TongDoanhThu = ThongKeTongDoanhThu();//Thống kê tổng doanh thu
            ViewBag.TongDDH = ThongKeDonHang();//Thống kê dơn hàng
            ViewBag.TongThanhVien = ThongKeThanhVien();//Thống kê thành viên
            //Kiểm tra xem id hợp lệ không
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DONDATHANG model = db.DONDATHANGs.SingleOrDefault(n => n.MADDH == id);
           
            //Kiểm tra đơn hàng có tồn tại không
            if (model == null)
            {
                return HttpNotFound();
            }
            //Lấy danh sách chi tiết đơn hàng để hiển thị cho người dùng thấy
            var lstChiTietDH = db.CHITIETDONDATHANGs.Where(n => n.MADDH == id);
            ViewBag.ListChiTietDH = lstChiTietDH;
            return View(model);
        }
        [HttpPost]
        public ActionResult DuyetDonHang(DONDATHANG ddh,int? id)
        {
            ViewBag.SoNguoiTruyCap = HttpContext.Application["SoNguoiTruyCap"].ToString();//Số lượng người truy cập từ application đã được tạo
            ViewBag.SoLuongNguoiOnline = HttpContext.Application["SoNguoiDangOnline"].ToString();//Lấy số lượng người đang truy cập
            ViewBag.TongDoanhThu = ThongKeTongDoanhThu();//Thống kê tổng doanh thu
            ViewBag.TongDDH = ThongKeDonHang();//Thống kê dơn hàng
            ViewBag.TongThanhVien = ThongKeThanhVien();//Thống kê thành viên

            //Truy vấn lấy ra dữ liệu của đơn hàn đó 
            DONDATHANG ddhUpdate = db.DONDATHANGs.Single(n => n.MADDH == id);
            ddhUpdate.DATHANHTOAN = ddh.DATHANHTOAN;
            ddhUpdate.TINHTRANGGIAO = ddh.TINHTRANGGIAO;
            UpdateModel(ddhUpdate);
            db.SaveChanges();
         
            //Lấy danh sách chi tiết đơn hàng để hiển thị cho người dùng thấy
            var lstChiTietDH = db.CHITIETDONDATHANGs.Where(n => n.MADDH == ddh.MADDH);
            ViewBag.ListChiTietDH = lstChiTietDH;
            var lst = db.CHITIETDONDATHANGs.Where(n => n.MADDH == ddh.MADDH).ToList();
            foreach (var item in lst)
            {
                if (ddhUpdate.DATHANHTOAN == 1)
                {

                    SANPHAM sp = db.SANPHAMs.Single(n => n.MASP == item.MASP);
                    sp.SOLUONGTON = sp.SOLUONGTON - item.SOLUONG;
                    UpdateModel(sp);
                    db.SaveChanges();
                }
            }
            //Gửi khách hàng 1 mail để xác nhận việc thanh toán 
            GuiEmail("Xác đơn hàng ", "duykhanhkontum123@gmail.com", "ksshop.com.vn@gmail.com", "google123456", "Đơn hàng của bạn đã được đặt thành công!");
            return View(ddhUpdate);
        }
        public void GuiEmail(string Title, string ToEmail, string FromEmail, string PassWord, string Content)
        {
            // goi email
            MailMessage mail = new MailMessage();
            mail.To.Add(ToEmail); // Địa chỉ nhận
            mail.From = new MailAddress(ToEmail); // Địa chửi gửi
            mail.Subject = Title;  // tiêu đề gửi
            mail.Body = Content;                 // Nội dung
            mail.IsBodyHtml = true;
            SmtpClient smtp = new SmtpClient();
            smtp.Host = "smtp.gmail.com"; // host gửi của Gmail
            smtp.Port = 587;               //port của Gmail
            smtp.UseDefaultCredentials = false;
            smtp.Credentials = new System.Net.NetworkCredential
            (FromEmail, PassWord);//Tài khoản password người gửi
            smtp.EnableSsl = true;   //kích hoạt giao tiếp an toàn SSL
            smtp.Send(mail);   //Gửi mail đi
        }

        public decimal ThongKeTongDoanhThu()
        {
            //Thống kê theo tất cả doanh thu
            decimal TongDoanhThu = db.CHITIETDONDATHANGs.Sum(n => n.SOLUONG * n.DONGIA);
            return TongDoanhThu;
        }
        public double ThongKeDonHang()
        {
            //Dếm đơn đặt hàng
            double slDDH = db.DONDATHANGs.Count();
            return slDDH;
        }
        public double ThongKeThanhVien()
        {
            //Dếm đơn đặt hàng
            double slTV = db.THANHVIENs.Count();
            return slTV;
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (db != null)
                    db.Dispose();
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WepSiteBanHang/WepSiteBanHang/Areas/Admin/Views/QuanLyDonHang/ChuaGiao.cshtml
@using WepSiteBanHang.Models;
@model IEnumerable<DonDatHang>
@{
    ViewBag.Title = "ChuaGiao";
    Layout = "~/Areas/Admin/Views/LayoutAD/AdinLayout.cshtml";
    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 20);
}

<h2>Quản lý đơn hàng (Danh sách đơn hàng chưa giao đã thanh toán)</h2>  <br />
@*Dùng boostrap tạo 1 tab control với các liên kết đến các view khác*@
<ul class="nav nav-tabs">
    <li role="presentation"><a href="@Url.Action("ChuaThanhToan","QuanLyDonHang")">Chưa thanh toán</a></li>
    <li role="presentation" class="active"><a href="@Url.Action("ChuaGiao", "QuanLyDonHang")">Chưa giao & Đã thanh toán</a></li>
    <li role="presentation"><a href="@Url.Action("DaGiaoDaThanhToan", "QuanLyDonHang")">Đã giao & Đã thanh toán</a></li>
</ul>

<br /><br />

@*Dùng control Webgrid thể hiện dữ liệu model là danh sách các đơn đặt hàng được
    truy vấn theo điều kiện từ controller*@
@grid.GetHtml(
    tableStyle: "table table-striped table-bordered table-hover divTable",
    headerStyle: "gridHead",
    footerStyle: "gridFooter",
    rowStyle: "gridRow",
    alternatingRowStyle: "gridAltRow",
    columns: grid.Columns(
    grid.Column("MaDDH", header: "Mã đơn hàng"), grid.Column("MaThanhVien", header: "Họ tên KH", format: p => p.MaThanhVien != null ? p.ThanhVien.HoTen : ""),  //Dùng toán tử 3 ngôi thay cho điều kiện if
        grid.Column("NgayDat", header: "Ngày đặt"),
        grid.Column("TinhTrangGiaoHang", header: "Tình trạng giao hàng"),
        grid.Column("NgayGiao", header: "Ngày giao"),
        grid.Column("DaThanhToan", header: "Đã thanh toán"),
        grid.Column("UuDai", header: "Ưu đãi"),

    grid.Column(format: p => @Html.ActionLink("Duyệt đơn hàng", "DuyetDonHang", new { id = p.MaDDH }, new { @target = "_blank" ,@class = "btn btn-info"}))

        ))

<style>
    .nav > li {
        background: rgba(0,0,0,.5);
    }

    .divTable {
        border: 1px solid #999999;
        text-align:center;
    }

        .divTable td {
            border: 1px solid #999999;
        }

    .gridHead {
        text-align:center;
          background-color:forestgreen;
    }

        .gridHead > th > a {
            color: #fff;
        }

    .gridFooter {
        font-weight: bold;
    }

    .divTable a {
        color: blue;
    }
    /*.gridRow {
        color:#fff;
        background-color:blueviolet;
    }
    .gridAltRow {
        color:#fff;
        background-color:darkorange;
    }*/
</style>

WepSiteBanHang/WepSiteBanHang/Areas/Admin/Views/QuanLyDonHang/ChuaThanhToan.cshtml
@using WepSiteBanHang.Models;
@model IEnumerable<DonDatHang>

@{
    ViewBag.Title = "ChuaThanhToan";
    Layout = "~/Areas/Admin/Views/LayoutAD/AdinLayout.cshtml";
    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 20);
}

<h2>Quản lý đơn hàng (Danh sách đơn hàng chưa thanh toán)</h2>
<br />
@*Tab quản lý các trạng thái của đơn hàng*@
<ul class="nav nav-tabs">
    <li role="presentation" class="active"><a href="@Url.Action("ChuaThanhToan","QuanLyDonHang")">Chưa thanh toán</a></li>
    <li role="presentation"><a href="@Url.Action("ChuaGiao", "QuanLyDonHang")">Chưa giao & Đã thanh toán</a></li>
    <li role="presentation"><a href="@Url.Action("DaGiaoDaThanhToan", "QuanLyDonHang")">Đã giao & Đã thanh toán</a></li>
</ul>       <br />
@*Dùng control Webgrid thể hiện dữ liệu model là danh sách các đơn đặt hàng được
    truy vấn theo điều kiện từ controller*@
@grid.GetHtml(
    tableStyle: "table table-striped table-bordered table-hover divTable",
    headerStyle: "gridHead",
    footerStyle: "gridFooter",
    rowStyle: "gridRow",
    alternatingRowStyle: "gridAltRow",
    columns: grid.Columns(
    grid.Column("MaDDH", header: "Mã đơn hàng"),
        grid.Column("MaThanhVien", header: "Họ tên KH", format: p => p.MaThanhVien != null ? p.ThanhVien.HoTen : ""), //Dùng toán tử 3 ngôi thay cho điều kiện if
        grid.Column("NgayDat", header: "Ngày đặt"),
        grid.Column("TinhTrangGiaoHang", header: "Tình trạng giao hàng"),
        grid.Column("NgayGiao", header: "Ngày giao"),
        grid.Column("DaThanhToan", header: "Đã thanh toán"),
        grid.Column("UuDai", header: "Ưu đãi"),

    grid.Column(format: p => @Html.ActionLink("Duyệt đơn hàng", "DuyetDonHang", new { id = p.MaDDH }, new { @target = "_blank", @class = "btn btn-info" }))

        ))

@*Css cho controller*@
<style>
    .nav > li {
        background: rgba(0,0,0,.5);
    }

    .divTable {
        border: 1px solid #999999;
    }

        .divTable td {
            border: 1px solid #999999;
        }

    .gridHead {
           background-color:forestgreen;
    }

        .gridHead > th > a {
            color: #fff;
        }

    .gridFooter {
        font-weight: bold;
    }

    .divTable a {
        color: blue;
    }
  
</style>

WepSiteBanHang/WepSiteBanHang/Areas/Admin/Views/QuanLyDonHang/DaGiaoDaThanhToan.cshtml
@using WepSiteBanHang.Models;
@model IEnumerable<DonDatHang>
@{
    ViewBag.Title = "DaGiaoDaThanhToan";
    Layout = "~/Areas/Admin/Views/LayoutAD/AdinLayout.cshtml";
    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 20);
}


<h2>Quản lý đơn hàng (Danh sách đơn hàng đã giao và thanh toán)</h2>      <br />
@*Dùng boostrap tạo 1 tab control với các liên kết đến các view khác*@
<ul class="nav nav-tabs">
    <li role="presentation"><a href="@Url.Action("ChuaThanhToan","QuanLyDonHang")">Chưa thanh toán</a></li>
    <li role="presentation"><a href="@Url.Action("ChuaGiao", "QuanLyDonHang")">Chưa giao & Đã thanh toán </a></li>
    <li role="presentation" class="active"><a href="@Url.Action("DaGiaoDaThanhToan", "QuanLyDonHang")">Đã giao & Đã thanh toán</a></li>
</ul>
<br />
@*Dùng control Webgrid thể hiện dữ liệu model là danh sách các đơn đặt hàng được
    truy vấn theo điều kiện từ controller*@
@grid.GetHtml(
    tableStyle: "table table-striped table-bordered table-hover divTable",
    headerStyle: "gridHead",
    footerStyle: "gridFooter",
    rowStyle: "gridRow",
    alternatingRowStyle: "gridAltRow",
    columns: grid.Columns(
    grid.Column("MaDDH", header: "Mã đơn hàng"),
            grid.Column("MaThanhVien", header: "Họ tên KH", format: p => p.MaThanhVien != null ? p.ThanhVien.HoTen : ""), //Dùng toán tử 3 ngôi thay cho điều kiện if
        grid.Column("NgayDat", header: "Ngày đặt"),
        grid.Column("TinhTrangGiaoHang", header: "Tình trạng giao hàng"),
        grid.Column("NgayGiao", header: "Ngày giao"),
        grid.Column("DaThanhToan", header: "Đã thanh toán"),
        grid.Column("UuDai", header: "Ưu đãi"),

    grid.Column(format: p => @Html.ActionLink("Duyệt đơn hàng", "DuyetDonHang", new { id = p.MaDDH }, new { @target = "_blank", @class = "btn btn-info" }))

        ))

<style>
    .nav > li {
        background: rgba(0,0,0,.5);
    }

    .divTable {
    
        border: 1px solid #999999;
    }

        .divTable td {
            border: 1px solid #999999;
        }

    .gridHead {
                 background-color:forestgreen;
    }

        .gridHead > th > a {
            color: #fff;
        }

    .gridFooter {
        font-weight: bold;
    }

    .divTable a {
        color: blue;
    }
    /*.gridRow {
        color:#fff;
        background-color:blueviolet;
    }
    .gridAltRow {
        color:#fff;
        background-color:darkorange;
    }*/
</style>

WepSiteBanHang/WepSiteBanHang/Areas/Admin/Views/QuanLyDonHang/DuyetDonHang.cshtml
@using WepSiteBanHang.Models;
@model DonDatHang

@{
    ViewBag.Title = "DuyetDonHang";
    Layout = "~/Areas/Admin/Views/LayoutAD/AdinLayout.cshtml";
}


<h2>Thông tin đơn hàng <font color="#f65e84">@Model.ThanhVien.HoTen</font></h2>
<br /><br />

@using (Html.BeginForm())
{
    <div class="ChiTietDonHang table">
        @{IEnumerable<ChiTietDonDatHang> lstChiTietDH = (IEnumerable<ChiTietDonDatHang>)ViewBag.ListChiTietDH;}
        <table class="table" id="table">
            @*Phần thông tin đơn hàng*@
            <tr>
                <td colspan="4">
                    <table style="width:100%;">
                        <tr>
                            <td>Mã đơn hàng: <b style="color:red;"> @Model.MaDDH @Html.Hidden("MaDDH", @Model.MaDDH)</b></td>
                            <td>Mã khách hàng: <b style="color:red;"> @Model.ThanhVien.MaThanhVien</b></td>
                            <td>Tên khách hàng: <b style="color:red;"> @Model.ThanhVien.HoTen</b></td>
                            <td>Ngày đặt: @Model.NgayDat.Value.ToString("dd/MM/yyyy")</td>
                            <td>Đã thanh toán: @Html.EditorFor(model => model.DaThanhToan)</td>
                            <td>Đã giao: @Html.EditorFor(model => model.TinhTrangGiaoHang)</td>
                        </tr>
                    </table>

                </td>
            </tr>



            @*Thông tin chi tiết đơn hàng*@


            <tr>
                <td><b>Sản phẩm</b></td>
                <td><b>Hình ảnh</b></td>
                <td><b>Số lượng đặt</b></td>
                <td><b>Đơn giá đặt</b></td>
            </tr>

            @foreach (var item in lstChiTietDH)
            {
                <tr>
                    <td>@item.SanPham.TenSP</td>
                    <td><img width="150" height="150" src="@Url.Content("~/Content/HinhAnhSP/"+item.SanPham.HinhAnh)" /></td>
                    <td>@item.SoLuong</td>
                    <td>@item.DonGia</td>
                </tr>
            }
            <tr>
                <td align="right" colspan="4">Tổng số lượng: @Model.ChiTietDonDatHangs.Sum(n => n.SoLuong)sản phẩm</td>
            </tr>
            <tr>
                <td align="right" colspan="4">Tổng tiền: @Model.ChiTietDonDatHangs.Sum(n => n.SanPham.DonGia).Value.ToString("#,##") đồng</td>
            </tr>
        </table>
        <br /><br />
        <input type="button" value="In đơn hàng" id="btnInDonHang" />
        <input type="submit" value="Lưu đơn hàng" id="btnInDonHang" />
    </div>
            }

<script>

    $("#btnInDonHang").click(function () {
        var content = "<table>" + $("#table").html() + "</table>";
        InDonHang(content);
    });

    //Phương thức in
    function InDonHang(content) {
        var printWindow = window.open('', '', 'height=400,width=800');
        printWindow.document.write('<html><head><title>DIV Contents</title>');
        printWindow.document.write('</head><body >');
        printWindow.document.write(content);
        printWindow.document.write('</body></html>');
        printWindow.document.close();
        printWindow.print();
    }

</script>