WepSiteBanHang/WepSiteBanHang/Controllers/TimKiemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WepSiteBanHang.Models;
using PagedList;
namespace WepSiteBanHang.Controllers
{
    public class TimKiemController : Controller
    {
        // GET: TimKiem
        DBBanHangEntities db = new DBBanHangEntities();
        public ActionResult KQTimKiem(string sTuKhoa, int? page)
        {
            if (Request.HttpMethod != "GET")
            {
                page = 1;
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            //tìm kiếm theo ten sản phẩm
            var lstSP = db.SANPHAMs.Where(n => n.TENSP.Contains(sTuKhoa));
            ViewBag.TuKhoa = sTuKhoa;
            return View(lstSP.OrderBy(n => n.TENSP).ToPagedList(pageNumber, pageSize));
        }
        [HttpPost]
        public ActionResult LayTuKhoaTimKiem(string sTuKhoa)
        {
            //Gọi về hàm get tìm kiếm
            return RedirectToAction("KQTimKiem", new { @sTuKhoa = sTuKhoa });
        }
        public ActionResult KQTimKiemPartial(string sTuKhoa,FormCollection col)
        {   
            int? gia = int.Parse(col["sGial"]);
            int gian = int.Parse(col["sGian"]);
            if (gia == gian)
            {
                var lstSP = db.SANPHAMs.Where(n => n.TENSP.Contains(sTuKhoa));
                ViewBag.TuKhoa = sTuKhoa;
                return PartialView(lstSP.OrderBy(n => n.DONGIA));
            }
            else
            {
                if (gian > gia)
                {
                    var lstSP = db.SANPHAMs.Where(n => n.TENSP.Contains(sTuKhoa)).Where(n => n.DONGIA > gia).Where(n => n.DONGIA < gian);
                    ViewBag.TuKhoa = sTuKhoa;
                    return PartialView(lstSP.OrderBy(n => n.DONGIA));
                }
                else
                {
                    var lstSP = db.SANPHAMs.Where(n => n.TENSP.Contains(sTuKhoa)).Where(n => n.DONGIA > gia);
                    ViewBag.TuKhoa = sTuKhoa;
                    return PartialView(lstSP.OrderBy(n => n.DONGIA));
                }
            }

            //tìm kiếm theo ten sản phẩm
     
            
        }
    }
    
}

WepSiteBanHang/WepSiteBanHang/Views/TimKiem/KQTimKiem.cshtml
@using WepSiteBanHang.Models;
@using PagedList.Mvc;
@model PagedList.IPagedList<SANPHAM>

@{
    ViewBag.Title = "KQTimKiem";
    Layout = "~/Views/Layout/ProductLayout.cshtml";
}
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
@*Form tìm kiếm ajax*@
@using (Ajax.BeginForm("KQTimKiemPartial", "TimKiem", new AjaxOptions { @UpdateTargetId = "KQTimKiem", InsertionMode = InsertionMode.Replace }))
{
   
        <div class="search">
            <input type="text" class="txtTimKiem text-primary" style="font-size:14px;text-align:center" value="" name="sTuKhoa" placeholder="Nhập vào tên sản phẩm" />
            
            <strong>Giá Từ </strong>
            <input type="text" class="txtTimKiem text-primary" style="font-size:14px;text-align:center" value="0" name="sGial" placeholder="Gia lon" />
            <strong>Đến</strong>
            <input type="text" class="txtTimKiem text-primary" style="font-size:14px;text-align:center" value="0" name="sGian" placeholder="Gia lon" /> 
            <input type="submit"  class="btn btn-success" value="Tìm kiếm" />
        </div>
    
}
        <div id="KQTimKiem">
            <div class="product-one">
                @foreach (var item in Model)
                {
                    <div class="col-md-3 product-left wow slideInLeft" style="padding:1px;margin:10px">
                        <div class="product-main simpleCart_shelfItem">
                            <a href="@Url.Action("XemChiTiet", "SanPham", new { id = item.MaSP })" class="mask"><img class="img-responsive zoom-img" src="@Url.Content("~/Content/HinhAnhSP/" + item.HinhAnh)" style="width:150px;height:150px" alt=""></a>
                            <div class="product-bottom">
                                <h3 style="height:30px;overflow:hidden">@item.TenSP</h3>

                                <h4><a class="item_add" href="#"><i>Giá</i></a> <span class="item_price">@item.DonGia.Value.ToString("#,##")VNĐ</span></h4>
                                <a style="margin:1% 30% 0;" onclick="AddToCart('@item.MaSP')" class="btn hvr-radial-in"><strong>Thêm Vào Giỏ</strong></a>
                            </div>
                            <div class="srch">
                               
                            </div>
                        </div>

                    </div>

                }

            </div>
            <div class="clearfix"> </div>
            <div class="dlink">
                Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount
                @Html.PagedListPager(Model, page => Url.Action("KQTimKiem", new { page = page, @sTuKhoa = ViewBag.TuKhoa }))
            </div>

        </div>
        <style>
            #btnTimKiem {
                background-color: #4cae4c;
                color: #fff;
                padding: 0;
                font-size: 1.1em;
                font-weight: 600;
                margin-right: 0;
                border-radius: 0;
                -webkit-border-radius: 3px;
                -moz-border-radius: 3px;
                -o-border-radius: 3px;
                outline: none;
                border: none;
                cursor: pointer;
                position: absolute;
                left: 304px;
                padding: 3px;
            }

            .txtTimKiem {
                width: 200px;
                border-bottom-left-radius:40px;
                border-bottom-right-radius:40px;
                border-top-left-radius:40px;
                border-top-right-radius:40px;
                border: 1px solid #000;
            }
        </style>

WepSiteBanHang/WepSiteBanHang/Views/TimKiem/KQTimKiemPartial.cshtml
@using WepSiteBanHang.Models;
@model IEnumerable<SANPHAM>

@{ 
   
}

<div class="product-one">

    @foreach (var item in Model)
    {
       
       
        <div class="col-md-3 product-left simpleCart_shelfItem" style="padding:1px;margin:10px">
            <div class="product-main simpleCart_shelfItem">
                <a href="@Url.Action("XemChiTiet", "SanPham", new { id = item.MaSP })" class="mask"><img class="img-responsive zoom-img" src="@Url.Content("~/Content/HinhAnhSP/" + item.HinhAnh)" style="width:150px;height:150px" alt=""></a>
                <div class="product-bottom">
                    <h3 style="height:30px;overflow:hidden">@item.TenSP</h3>

                    <h4><a class="item_add" href="#"><i>Giá</i></a> <span class="item_price">@item.DonGia.Value.ToString("#,##") VNĐ</span></h4>
                    <a style="margin:1% 30% 0;" onclick="AddToCart('@item.MaSP')" class="btn hvr-radial-in"><strong>Thêm Vào Giỏ</strong></a>
                </div>
                <div class="srch">
                   
                </div>
            </div>

        </div>

    }

</div>
<div class="clearfix"> </div>